In [118]:
import pandas as pd

#carregando e unindo os dados em um dataset
r_cols = ['user_id', 'movie_id', 'rating']
ratings = pd.read_csv('data/u.data', sep='\t', names=r_cols, usecols=range(3))

m_cols = ['movie_id', 'title']
movies = pd.read_csv('data/u.item', sep='|', names=m_cols, usecols=range(2), encoding='ISO-8859-1')

ratings = pd.merge(movies, ratings)

ratings.head()

   movie_id             title  user_id  rating
0         1  Toy Story (1995)      308       4
1         1  Toy Story (1995)      287       5
2         1  Toy Story (1995)      148       4
3         1  Toy Story (1995)      280       4
4         1  Toy Story (1995)       66       3

In [119]:
#modificando o formato do dataset

movieRatings = ratings.pivot_table(index=['user_id'], columns=['title'], values=['rating'])
movieRatings.head()

                           rating                                     \
title   'Til There Was You (1997) 1-900 (1994) 101 Dalmatians (1996)
user_id
0                             NaN          NaN                   NaN
1                             NaN          NaN                   2.0
2                             NaN          NaN                   NaN
3                             NaN          NaN                   NaN
4                             NaN          NaN                   NaN

                                                                    \
title   12 Angry Men (1957) 187 (1997) 2 Days in the Valley (1996)
user_id
0                       NaN        NaN                         NaN
1                       5.0        NaN                         NaN
2                       NaN        NaN                         NaN
3                       NaN        2.0                         NaN
4                       NaN        NaN                         NaN

                                                                          \
title   20,000 Leagues Under the Sea (1954) 2001: A Space Odyssey (1968)
user_id
0                                       NaN                          NaN
1                                       3.0                          4.0
2                                       NaN                          NaN
3                                       NaN                          NaN
4                                       NaN                          NaN

                                                                          ...  \
title   3 Ninjas: High Noon At Mega Mountain (1998) 39 Steps, The (1935)  ...
user_id                                                                   ...
0                                               NaN                  NaN  ...
1                                               NaN                  NaN  ...
2                                               1.0                  NaN  ...
3                                               NaN                  NaN  ...
4                                               NaN                  NaN  ...

                                                                         \
title   Yankee Zulu (1994) Year of the Horse (1997) You So Crazy (1994)
user_id
0                      NaN                      NaN                 NaN
1                      NaN                      NaN                 NaN
2                      NaN                      NaN                 NaN
3                      NaN                      NaN                 NaN
4                      NaN                      NaN                 NaN

                                                                          \
title   Young Frankenstein (1974) Young Guns (1988) Young Guns II (1990)
user_id
0                             NaN               NaN                  NaN
1                             5.0               3.0                  NaN
2                             NaN               NaN                  NaN
3                             NaN               NaN                  NaN
4                             NaN               NaN                  NaN

                                                                               \
title   Young Poisoner's Handbook, The (1995) Zeus and Roxanne (1997) unknown
user_id
0                                         NaN                     NaN     NaN
1                                         NaN                     NaN     4.0
2                                         NaN                     NaN     NaN
3                                         NaN                     NaN     NaN
4                                         NaN                     NaN     NaN


title   Á köldum klaka (Cold Fever) (1994)
user_id
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN

[5 rows x 1664 columns]

In [120]:
movieRatings.columns = movieRatings.columns.get_level_values(1)
starWarsRatings = movieRatings['Star Wars (1977)'] # avaliação do star wars 
starWarsRatings

user_id
0      5.0
1      5.0
2      5.0
3      NaN
4      5.0
      ...
939    NaN
940    4.0
941    NaN
942    5.0
943    4.0
Name: Star Wars (1977), Length: 944, dtype: float64

In [121]:
#construindo a correlação entre star wars e os outros filmes, removendo os valores nulos
#e transformando isso num dataset

similarMovies = movieRatings.corrwith(starWarsRatings)
similarMovies = similarMovies.dropna()
df = pd.DataFrame(similarMovies)
df.head(10)

/home/lucasarenhardt/.local/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/lucasarenhardt/.local/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/home/lucasarenhardt/.local/lib/python3.10/site-packages/numpy/lib/function_base.py:2889: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/home/lucasarenhardt/.local/lib/python3.10/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/home/lucasarenhardt/.local/lib/python3.10/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

                                            0
title
'Til There Was You (1997)            0.872872
1-900 (1994)                        -0.645497
101 Dalmatians (1996)                0.211132
12 Angry Men (1957)                  0.184289
187 (1997)                           0.027398
2 Days in the Valley (1996)          0.066654
20,000 Leagues Under the Sea (1954)  0.289768
2001: A Space Odyssey (1968)         0.230884
39 Steps, The (1935)                 0.106453
8 1/2 (1963)                        -0.142977

In [122]:
#ordenando os filmes por similaridade
similarMovies.sort_values(ascending=False)

title
Hollow Reed (1996)            1.0
Commandments (1997)           1.0
Cosi (1996)                   1.0
No Escape (1994)              1.0
Stripes (1981)                1.0
                             ...
For Ever Mozart (1996)       -1.0
Frankie Starlight (1995)     -1.0
I Like It Like That (1994)   -1.0
American Dream (1990)        -1.0
Theodore Rex (1995)          -1.0
Length: 1410, dtype: float64

In [123]:
import numpy as np

#criando um novo dataset com o número de pessoas que avaliaram o filme e a média das avaliações
movieStats = ratings.groupby('title').agg({'rating': ['size', 'mean']})
movieStats.head()

                          rating
                            size      mean
title
'Til There Was You (1997)      9  2.333333
1-900 (1994)                   5  2.600000
101 Dalmatians (1996)        109  2.908257
12 Angry Men (1957)          125  4.344000
187 (1997)                    41  3.024390

In [124]:
#filtrando apenas os filmes que foram avaliados por mais de 100 pessoas
popularMovies = movieStats['rating']['size'] >= 100
movieStats[popularMovies].sort_values([('rating', 'mean')], ascending=False)[:15]

                                       rating
                                         size      mean
title
Close Shave, A (1995)                     112  4.491071
Schindler's List (1993)                   298  4.466443
Wrong Trousers, The (1993)                118  4.466102
Casablanca (1942)                         243  4.456790
Shawshank Redemption, The (1994)          283  4.445230
Rear Window (1954)                        209  4.387560
Usual Suspects, The (1995)                267  4.385768
Star Wars (1977)                          584  4.359589
12 Angry Men (1957)                       125  4.344000
Citizen Kane (1941)                       198  4.292929
To Kill a Mockingbird (1962)              219  4.292237
One Flew Over the Cuckoo's Nest (1975)    264  4.291667
Silence of the Lambs, The (1991)          390  4.289744
North by Northwest (1959)                 179  4.284916
Godfather, The (1972)                     413  4.283293

In [125]:
movieStats[popularMovies]['rating']

                                              size      mean
title
101 Dalmatians (1996)                          109  2.908257
12 Angry Men (1957)                            125  4.344000
2001: A Space Odyssey (1968)                   259  3.969112
Absolute Power (1997)                          127  3.370079
Abyss, The (1989)                              151  3.589404
...                                            ...       ...
Willy Wonka and the Chocolate Factory (1971)   326  3.631902
Wizard of Oz, The (1939)                       246  4.077236
Wrong Trousers, The (1993)                     118  4.466102
Young Frankenstein (1974)                      200  3.945000
Young Guns (1988)                              101  3.207921

[338 rows x 2 columns]

In [126]:
#unindo o dataframe com a similaridade
df = movieStats[popularMovies]['rating'].join(pd.DataFrame(similarMovies, columns=['similarity']))
df.head()

                              size      mean  similarity
title
101 Dalmatians (1996)          109  2.908257    0.211132
12 Angry Men (1957)            125  4.344000    0.184289
2001: A Space Odyssey (1968)   259  3.969112    0.230884
Absolute Power (1997)          127  3.370079    0.085440
Abyss, The (1989)              151  3.589404    0.203709

In [128]:
df.sort_values(['similarity'], ascending=False)[:15]

                                                    size      mean  similarity
title
Star Wars (1977)                                     584  4.359589    1.000000
Empire Strikes Back, The (1980)                      368  4.206522    0.748353
Return of the Jedi (1983)                            507  4.007890    0.672556
Raiders of the Lost Ark (1981)                       420  4.252381    0.536117
Austin Powers: International Man of Mystery (1997)   130  3.246154    0.377433
Sting, The (1973)                                    241  4.058091    0.367538
Indiana Jones and the Last Crusade (1989)            331  3.930514    0.350107
Pinocchio (1940)                                     101  3.673267    0.347868
Frighteners, The (1996)                              115  3.234783    0.332729
L.A. Confidential (1997)                             297  4.161616    0.319065
Wag the Dog (1997)                                   137  3.510949    0.318645
Dumbo (1941)                                         123  3.495935    0.317656
Bridge on the River Kwai, The (1957)                 165  4.175758    0.316580
Philadelphia Story, The (1940)                       104  4.115385    0.314272
Miracle on 34th Street (1994)                        101  3.722772    0.310921

In [130]:
import pandas as pd

#carregando os dados pro dataset
r_cols = ['user_id', 'movie_id', 'rating']
ratings = pd.read_csv('data/u.data', sep='\t', names=r_cols, usecols=range(3))

m_cols = ['movie_id', 'title']
movies = pd.read_csv('data/u.item', sep='|', names=m_cols, usecols=range(2), encoding='ISO-8859-1')

ratings = pd.merge(movies, ratings)
ratings.head()

   movie_id             title  user_id  rating
0         1  Toy Story (1995)      308       4
1         1  Toy Story (1995)      287       5
2         1  Toy Story (1995)      148       4
3         1  Toy Story (1995)      280       4
4         1  Toy Story (1995)       66       3

In [131]:
#modificando o formato do dataset
userRatings = ratings.pivot_table(index=['user_id'], columns=['title'], values='rating')
userRatings.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
#matriz de correlação entre as avaliações dos filmes
corrMatrix = userRatings.corr()
corrMatrix.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),1.0,NaN,-1.000000,-0.500000,-0.500000,0.522233,NaN,-0.426401,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1-900 (1994),NaN,1.0,NaN,NaN,NaN,NaN,NaN,-0.981981,NaN,NaN,...,NaN,NaN,NaN,-0.944911,NaN,NaN,NaN,NaN,NaN,NaN
101 Dalmatians (1996),-1.0,NaN,1.000000,-0.049890,0.269191,0.048973,0.266928,-0.043407,NaN,0.111111,...,NaN,-1.000000,NaN,0.158840,0.119234,0.680414,-4.875600e-17,0.707107,NaN,NaN
12 Angry Men (1957),-0.5,NaN,-0.049890,1.000000,0.666667,0.256625,0.274772,0.178848,NaN,0.457176,...,NaN,NaN,NaN,0.096546,0.068944,-0.361961,1.443376e-01,1.000000,1.0,NaN
187 (1997),-0.5,NaN,0.269191,0.666667,1.000000,0.596644,NaN,-0.554700,NaN,1.000000,...,NaN,0.866025,NaN,0.455233,-0.500000,0.500000,4.753271e-01,NaN,NaN,NaN

In [135]:
#filtrando apenas os filmes que forma avaliados por mais de 100 pessoas
corrMatrix = userRatings.corr(method='pearson', min_periods=100)
corrMatrix.head()

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1-900 (1994),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101 Dalmatians (1996),NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12 Angry Men (1957),NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187 (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
#removendo os valores nulos
myRatings = userRatings.loc[0].dropna()
myRatings

title
Empire Strikes Back, The (1980)    5.0
Gone with the Wind (1939)          1.0
Star Wars (1977)                   5.0
Name: 0, dtype: float64

In [138]:
simCandidates = pd.Series() 

#adicionar os filmes similares
for i in range(0, len(myRatings.index)):
    print('Adding sims for ' + str(myRatings.index[i]) + '...')
    sims = corrMatrix[myRatings.index[i]].dropna()
    sims = sims.map(lambda x: x * myRatings[i])
    simCandidates = simCandidates._append(sims)

print('Sorting...')

#ordenando e mostrando os filmes
simCandidates.sort_values(inplace=True, ascending=False)
print(simCandidates.head(10))

Adding sims for Empire Strikes Back, The (1980)...
Adding sims for Gone with the Wind (1939)...
Adding sims for Star Wars (1977)...
Sorting...
Empire Strikes Back, The (1980)                       5.000000
Star Wars (1977)                                      5.000000
Empire Strikes Back, The (1980)                       3.741763
Star Wars (1977)                                      3.741763
Return of the Jedi (1983)                             3.606146
Return of the Jedi (1983)                             3.362779
Raiders of the Lost Ark (1981)                        2.693297
Raiders of the Lost Ark (1981)                        2.680586
Austin Powers: International Man of Mystery (1997)    1.887164
Sting, The (1973)                                     1.837692
dtype: float64

/tmp/ipykernel_81603/966915774.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sims = sims.map(lambda x: x * myRatings[i])
/tmp/ipykernel_81603/966915774.py:8: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  simCandidates = simCandidates._append(sims)
/tmp/ipykernel_81603/966915774.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sims = sims.map(lambda x: x * myRatings[i])
/tmp/ipykernel_81603/966915774.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sims = sims.map(lambda x: x * myRatings[i])

In [139]:
#utilizando o gorupby para somar a nota dos filmes que aparecem mais de uma vez
simCandidates = simCandidates.groupby(simCandidates.index).sum() 
simCandidates.sort_values(inplace=True, ascending=False)
simCandidates.head(10)

Empire Strikes Back, The (1980)              8.877450
Star Wars (1977)                             8.870971
Return of the Jedi (1983)                    7.178172
Raiders of the Lost Ark (1981)               5.519700
Indiana Jones and the Last Crusade (1989)    3.488028
Bridge on the River Kwai, The (1957)         3.366616
Back to the Future (1985)                    3.357941
Sting, The (1973)                            3.329843
Cinderella (1950)                            3.245412
Field of Dreams (1989)                       3.222311
dtype: float64

In [140]:
filteredSims = simCandidates.drop(myRatings.index)
filteredSims

Return of the Jedi (1983)                    7.178172
Raiders of the Lost Ark (1981)               5.519700
Indiana Jones and the Last Crusade (1989)    3.488028
Bridge on the River Kwai, The (1957)         3.366616
Back to the Future (1985)                    3.357941
                                               ...
Annie Hall (1977)                           -0.511775
Real Genius (1985)                          -0.552871
Remains of the Day, The (1993)              -0.560337
This Is Spinal Tap (1984)                   -0.636474
First Wives Club, The (1996)                -0.972480
Length: 265, dtype: float64